### ISSUE TITLE
Remove hash from repo broke variant

### ISSUE THREAD

**Issue by matbech** [boostorg/functional#8]
The commit Remove hash from repo https://github.com/boostorg/functional/commit/16a4ab6de637ba4bd6b8a592a5d13623341d015c broke boost's variant.
boost variant includes the removed:
#include <boost/functional/hash_fwd.hpp>
https://github.com/boostorg/variant/blob/develop/include/boost/variant/detail/hash_variant.hpp#L24

**Comment by danieljames** [comment]
It's in the new container_hash module, if you use `git submodule update --init` to update the super project, it should be automatically checked out.

**Comment by matbech** [comment]
Thank you. It's working now.
